import { SportEvent } from '@/types/events';

export const mockEvents: SportEvent[] = [
  {
    idEvent: '1',
    strEvent: 'Manchester United vs Liverpool',
    strLeague: 'English Premier League',
    strSport: 'Soccer',
    dateEvent: '2026-02-20',
    strTime: '15:00:00',
    strHomeTeam: 'Manchester United',
    strAwayTeam: 'Liverpool',
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intHomeScore: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Old Trafford',
    strCountry: 'England',
  },
  {
    idEvent: '2',
    strEvent: 'Los Angeles Lakers vs Boston Celtics',
    strLeague: 'NBA',
    strSport: 'Basketball',
    dateEvent: '2026-02-18',
    strTime: '20:30:00',
    strHomeTeam: 'Los Angeles Lakers',
    strAwayTeam: 'Boston Celtics',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Crypto.com Arena',
    strCountry: 'USA',
  },
  {
    idEvent: '3',
    strEvent: 'Real Madrid vs Barcelona',
    strLeague: 'Spanish La Liga',
    strSport: 'Soccer',
    dateEvent: '2026-02-19',
    strTime: '21:00:00',
    strHomeTeam: 'Real Madrid',
    strAwayTeam: 'Barcelona',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Santiago Bernabéu',
    strCountry: 'Spain',
  },
  {
    idEvent: '4',
    strEvent: 'New York Yankees vs Boston Red Sox',
    strLeague: 'MLB',
    strSport: 'Baseball',
    dateEvent: '2026-02-21',
    strTime: '19:00:00',
    strHomeTeam: 'New York Yankees',
    strAwayTeam: 'Boston Red Sox',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Yankee Stadium',
    strCountry: 'USA',
  },
  {
    idEvent: '5',
    strEvent: 'Bayern Munich vs Borussia Dortmund',
    strLeague: 'German Bundesliga',
    strSport: 'Soccer',
    dateEvent: '2026-02-22',
    strTime: '18:30:00',
    strHomeTeam: 'Bayern Munich',
    strAwayTeam: 'Borussia Dortmund',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Allianz Arena',
    strCountry: 'Germany',
  },
  {
    idEvent: '6',
    strEvent: 'Golden State Warriors vs LA Clippers',
    strLeague: 'NBA',
    strSport: 'Basketball',
    dateEvent: '2026-02-17',
    strTime: '22:00:00',
    strHomeTeam: 'Golden State Warriors',
    strAwayTeam: 'LA Clippers',
    intHomeScore: '108',
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: '112',
    strThumb: null,
    strStatus: 'FT',
    strVenue: 'Chase Center',
    strCountry: 'USA',
  },
  {
    idEvent: '7',
    strEvent: 'Chelsea vs Arsenal',
    strLeague: 'English Premier League',
    strSport: 'Soccer',
    dateEvent: '2026-02-23',
    strTime: '17:30:00',
    strHomeTeam: 'Chelsea',
    strAwayTeam: 'Arsenal',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Stamford Bridge',
    strCountry: 'England',
  },
  {
    idEvent: '8',
    strEvent: 'Miami Heat vs Brooklyn Nets',
    strLeague: 'NBA',
    strSport: 'Basketball',
    dateEvent: '2026-02-19',
    strTime: '19:30:00',
    strHomeTeam: 'Miami Heat',
    strAwayTeam: 'Brooklyn Nets',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'FTX Arena',
    strCountry: 'USA',
  },
  {
    idEvent: '9',
    strEvent: 'Dallas Cowboys vs Philadelphia Eagles',
    strLeague: 'NFL',
    strSport: 'American Football',
    dateEvent: '2026-02-24',
    strTime: '20:15:00',
    strHomeTeam: 'Dallas Cowboys',
    strAwayTeam: 'Philadelphia Eagles',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'AT&T Stadium',
    strCountry: 'USA',
  },
  {
    idEvent: '10',
    strEvent: 'Toronto Maple Leafs vs Montreal Canadiens',
    strLeague: 'NHL',
    strSport: 'Ice Hockey',
    dateEvent: '2026-02-18',
    strTime: '19:00:00',
    strHomeTeam: 'Toronto Maple Leafs',
    strAwayTeam: 'Montreal Canadiens',
    intHomeScore: '3',
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: '2',
    strThumb: null,
    strStatus: 'FT',
    strVenue: 'Scotiabank Arena',
    strCountry: 'Canada',
  },
  {
    idEvent: '11',
    strEvent: 'Paris Saint-Germain vs Olympique Marseille',
    strLeague: 'French Ligue 1',
    strSport: 'Soccer',
    dateEvent: '2026-02-25',
    strTime: '21:00:00',
    strHomeTeam: 'Paris Saint-Germain',
    strAwayTeam: 'Olympique Marseille',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'Parc des Princes',
    strCountry: 'France',
  },
  {
    idEvent: '12',
    strEvent: 'Chicago Bulls vs Milwaukee Bucks',
    strLeague: 'NBA',
    strSport: 'Basketball',
    dateEvent: '2026-02-20',
    strTime: '20:00:00',
    strHomeTeam: 'Chicago Bulls',
    strAwayTeam: 'Milwaukee Bucks',
    intHomeScore: null,
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strPoster: null,
    intAwayScore: null,
    strThumb: null,
    strStatus: 'NS',
    strVenue: 'United Center',
    strCountry: 'USA',
  },
];
